version: 1.0.{build}
before_build:
- ps: >-
    if($env:APPVEYOR_REPO_BRANCH -eq "master"){

    if($env:APPVEYOR_REPO_TAG -eq $true){

    $env:CONFIGURATION = "Release"

    Write-Host "Switch to Release configuration"

    }

    else{

    $env:CONFIGURATION = "Debug"

    Write-Host "Switch to Debug configuration"


    }

    }
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: if %APPVEYOR_REPO_BRANCH% == master "..\DBMS\DBMS\packages\Tools.InnoSetup.5.5.6\tools\ISCC.exe" "..\DBMS\InstallScript.iss"
  - cmd: appveyor PushArtifact ..\DBMS\Output\setup.exe
artifacts:
- path: ..\DBMS\Output\setup.exe
  name: setup.exe


cache:
  - packages -> **\.nuget\packages.config

deploy: 
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: DBMS release of v$(APPVEYOR_BUILD_VERSION)
    description: New release of DBMS
    auth_token: 
      secure: BebGrkEs2HZ+L6EN5TNWC+BYBi0g1yxA9XssKd4lNGSMK0ynNjbnroMiMJpYeiCf
    artifact: Setup
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: false